### ISSUE TITLE
The game sometimes crashes when Mario jumps on a Goomba or Goombario Headbonks a Goomba, the game crashes.

### ISSUE THREAD

**Issue by SpecterSpectrum** [Shade-Blade/PMDarkStarEdition#2]
The hammer hasn't caused the game to crash yet. I'm not sure if this applies to all enemies or just goombas, since i can't even get past the second room due to this. Is this a previously seen issue? If so, how can i fix it?
![Screenshot (52)](https://user-images.githubusercontent.com/131496995/233746420-0cef20f9-080b-4e75-8f93-d287c131587f.png)

**Comment by Shade-Blade** [comment]
This bug is probably caused by using Project 64 on Windows 11
